### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/basil-loader#461]
- [x] webignition/basil-data-validator#70
- [x] webignition/basil-model-provider#33
- [x] webignition/basil-parser#105
- [x] webignition/basil-resolver#49
- [x] webignition/php-basil-context-aware-exception#8
- [x] webignition/php-path-resolver#7
